import type { DefaultSharedModuleContext, ExecuteCommandAcceptor, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { AbstractExecuteCommandHandler, createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { MyRobotGeneratedModule, MyRobotGeneratedSharedModule } from './generated/module.js';
import { MyRobotValidator, registerValidationChecks } from './my-robot-validator.js';
import { MyRobotAcceptWeaver, weaveAcceptMethods } from './visitorGenerator/accept-weaver.js';
import { parseAndGenerate, parseAndValidate } from '../web/index.js';


/**
 * Declaration of custom services - add your own service classes here.
 */
export type MyRobotAddedServices = {
    validation: {
        MyRobotValidator: MyRobotValidator,
        MyRobotAcceptWeaver: MyRobotAcceptWeaver
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MyRobotServices = LangiumServices & MyRobotAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MyRobotModule: Module<MyRobotServices, PartialLangiumServices & MyRobotAddedServices> = {
    validation: {
        MyRobotValidator: () => new MyRobotValidator(),
        MyRobotAcceptWeaver: () => new MyRobotAcceptWeaver()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMyRobotServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MyRobot: MyRobotServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MyRobotGeneratedSharedModule
    );
    const MyRobot = inject(
        createDefaultModule({ shared }),
        MyRobotGeneratedModule,
        MyRobotModule
    );
    shared.lsp.ExecuteCommandHandler = new MyRobotCommandHandler();
    shared.ServiceRegistry.register(MyRobot);
    registerValidationChecks(MyRobot);
    weaveAcceptMethods(MyRobot);
    return { shared, MyRobot };
}

class MyRobotCommandHandler extends AbstractExecuteCommandHandler {
    registerCommands(acceptor: ExecuteCommandAcceptor): void {
        // accept a single command called 'parseAndGenerate'
        acceptor('parseAndGenerate', args => {
            // invoke generator on this data, and return the response
            return parseAndGenerate(args[0]);
        });

        acceptor('parseAndValidate', args => {
            // invoke generator on this data, and return the response
            return parseAndValidate(args[0]);
        });
    }
}
