import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { MyRobotGeneratedModule, MyRobotGeneratedSharedModule } from './generated/module.js';
import { MyRobotValidator, registerValidationChecks } from './my-robot-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MyRobotAddedServices = {
    validation: {
        MyRobotValidator: MyRobotValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MyRobotServices = LangiumServices & MyRobotAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MyRobotModule: Module<MyRobotServices, PartialLangiumServices & MyRobotAddedServices> = {
    validation: {
        MyRobotValidator: () => new MyRobotValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMyRobotServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MyRobot: MyRobotServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MyRobotGeneratedSharedModule
    );
    const MyRobot = inject(
        createDefaultModule({ shared }),
        MyRobotGeneratedModule,
        MyRobotModule
    );
    shared.ServiceRegistry.register(MyRobot);
    registerValidationChecks(MyRobot);
    return { shared, MyRobot };
}
